### PR TITLE
osu-lazer-bin: fix update script

### LINKED ISSUE #55: `osu-lazer`'s `info.json` is empty
The scheduled update yesterday seems to have broken `osu-lazer`, resulting in an empty `info.json`. Looking through the workflow's logs:
```
error: unable to download 'https://github.com/ppy/osu/releases/download/2023.301.0/osu.AppImage': HTTP error 404

       response body:

       ���/Qp�/�KM�t�       
```

Seems like `osu-lazer` upstream made a [tag yesterday](https://github.com/ppy/osu/releases/tag/2023.301.0) that had no release binaries, only source code, hence the above error. We should probably add a check to the update script.

### PR DESCRIPTION
**Pull request by fufexan**
Checks whether the required AppImage exists in the release, otherwise doesn't
update info.json.
Fixes #55

### CODE REVIEW

File: pkgs/osu-lazer-bin/update.sh [hunk 1]
```diff
@@ -6,8 +6,11 @@ oldversion=$(jq -r '.version' "$info")
 url="https://github.com/ppy/osu/releases/download/${version}/osu.AppImage"
 
 if [ "$oldversion" != "$version" ]; then
-  nix store prefetch-file "$url" --json > "$info"
-  jq --arg version "$version" '.version = $version' "$info" | sponge "$info"
+  if nix store prefetch-file "$url" --json >"$info"; then
+    jq --arg version "$version" '.version = $version' "$info" | sponge "$info"
```
Comment (PlayerNameHere) [inline pkgs/osu-lazer-bin/update.sh:10]: This will still cause `info.json` to be empty if the AppImage isn't available (tested by giving a bogus URL since `osu-lazer` has now released the AppImage). The `>"$info"` occurs no matter the exit status of `nix store prefetch-file`.

Maybe something like:
```suggestion
  if output=$(nix store prefetch-file "$url" --json); then
    jq --arg version "$version" '.version = $version' <<< "$output" > "$info"
```
This would eliminate the need for `sponge` and consequently `moreutils` as well.

**Review by PlayerNameHere — CHANGES_REQUESTED** [review]
I think this fix is sufficient; can't really think of anything else. Like you said, `npins` doesn't have a way to track releases instead of tags. I believe `nvfetcher` can do that, but I don't think there's much gain in switching.

File: pkgs/osu-lazer-bin/update.sh (hunk 1 above)
Comment (fufexan) [reply pkgs/osu-lazer-bin/update.sh]: Thanks!
